apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-auth
  template:
    metadata:
      labels:
        app: ticket-auth
    spec:
      containers:
        - name: ticket-auth
          image: dipzcoded/ticketing-auth
          env:
            - name: MONGO_URI
              value: mongodb://auth-mongodb-srv:27017/auth
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: ticket-auth-srv
spec:
  selector:
    app: ticket-auth
  ports:
    - name: ticket-auth
      protocol: TCP
      port: 3200
      targetPort: 3200
